name: Build
on:
  push:
    branches: [master]

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_TAG_PREFIX: ghcr.io/${{ github.repository_owner }}/utstatsdb
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build:
    name: Build Containers
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Build and push app image
        uses: docker/build-push-action@v4
        with:
          file: ./Containerfile
          tags: |
            ${{ env.IMAGE_TAG_PREFIX }}-app:${{ github.sha }}
            ${{ env.IMAGE_TAG_PREFIX }}-app:${{ github.ref_name }}
          push: true

      - name: Build and push http image
        uses: docker/build-push-action@v4
        with:
          file: ./Containerfile.http
          tags: |
            ${{ env.IMAGE_TAG_PREFIX }}-http:${{ github.sha }}
            ${{ env.IMAGE_TAG_PREFIX }}-http:${{ github.ref_name }}
          push: true
